"""initTable22

Revision ID: 09b9188a068e
Revises: c67a6aa6d83f
Create Date: 2023-09-29 18:55:35.512559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09b9188a068e'
down_revision = 'c67a6aa6d83f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
