"""autogenerate

Revision ID: 0d01096df7cc
Revises: 278c6545269d
Create Date: 2023-09-29 19:34:32.029670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d01096df7cc'
down_revision = '278c6545269d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
