"""initTable22

Revision ID: 20a167a51b43
Revises: 09b9188a068e
Create Date: 2023-09-29 18:56:55.013770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20a167a51b43'
down_revision = '09b9188a068e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
