"""initTable22

Revision ID: 273758c0e858
Revises: 735561cb1301
Create Date: 2023-09-29 19:10:50.554087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '273758c0e858'
down_revision = '735561cb1301'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
