"""initTable22

Revision ID: 49af55191b15
Revises: 20a167a51b43
Create Date: 2023-09-29 18:57:25.705192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49af55191b15'
down_revision = '20a167a51b43'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
