"""initTable22

Revision ID: 55dcd2a1263a
Revises: cde4a466ad25
Create Date: 2023-09-29 18:31:29.534449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55dcd2a1263a'
down_revision = 'cde4a466ad25'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
