"""initTable22

Revision ID: 735561cb1301
Revises: afd4c57f09bc
Create Date: 2023-09-29 19:09:53.339559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '735561cb1301'
down_revision = 'afd4c57f09bc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admins')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='admins_pkey'),
    sa.UniqueConstraint('email', name='admins_email_key')
    )
    # ### end Alembic commands ###
