"""initTable22

Revision ID: c67a6aa6d83f
Revises: 55dcd2a1263a
Create Date: 2023-09-29 18:39:48.902112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c67a6aa6d83f'
down_revision = '55dcd2a1263a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
